### PR TITLE
fix(plugins): use primaryMirror instead of baseDomain for replication targets

### LINKED ISSUE #1916: 🐛 [BUG] - OCI replication targets baseDomain instead of primaryMirror
### Priority

(Medium) I'm annoyed but I'll live

### Description

`EnsureReplicated` constructs the `crane.Manifest` target using `baseDomain` instead of `primaryMirror`. This may cause replication to fail:
- with auth rejection (credentials are issued for `primaryMirror`) 
- with missing tags (artifact not yet available on the read-only `baseDomain` endpoint).

### Reproduction steps

```bash
1. Configure an Organization mirror where primaryMirror is not equal to baseDomain (keppel.eu-de-1.cloud.sap vs keppel.global.cloud.sap)
2. Create a PluginDefinition with an OCI chart from ghcr.io
3. Replication calls crane.Manifest against baseDomain instead of primaryMirror
4. Fails with auth rejection or missing tag
```

### Manifests

```yaml
primaryMirror: "registry.us-east-1.example.com"
registryMirrors:
  ghcr.io:
    baseDomain: "registry.cdn.example.com"
    subPath: "ghcr-io-mirror"
  docker.io:
    baseDomain: "registry.cdn.example.com"
    subPath: "dockerhub-mirror"
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### PR DESCRIPTION
**Pull request by mikolajkucinski**
## Description

This PR fixes `EnsureReplicated` constructing `crane.Manifest` targets using `baseDomain` instead of `primaryMirror` 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Fixes https://github.com/cloudoperators/greenhouse/issues/1916

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🤝 Documentation pages updated
- [x] 🙅 no documentation needed
- [ ] (if applicable) generated OpenAPI docs for CRD changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: internal/ocimirror/image_mirror.go [hunk 1]
```diff
@@ -69,11 +69,18 @@ func (m *ImageMirror) EnsureReplicated(ctx context.Context, ociRef string) (repl
 		return mirroredRef, manifest, err
 	}
```
Comment (abhijith-darshan) [inline internal/ocimirror/image_mirror.go:79]: What about this section?

Comment (IvoGoman) [reply internal/ocimirror/image_mirror.go:79]: handled here: https://github.com/cloudoperators/greenhouse/pull/1917/changes#diff-e8130128a1fa779f346b31dc4bbeb485953cce21904112b26c9cac4b0f0f20dbR177

**Review by IvoGoman — DISMISSED** [review]

**Review by IvoGoman — APPROVED** [review]

**Review by abhijith-darshan — APPROVED** [review]
