### PR TITLE
Fix/helm controller does not update the release

### LINKED ISSUE #459: 🐛 [BUG] - HelmController does not update release if hooks are changed
### Priority

(Urgent) I can't use Greenhouse

### Description

The HelmController does not compute a diff between rendered HelmChart and deployed Release, if only Helm Chart Hooks are changed. These hooks are not part of the manifest.
The Helm Diff needs to consider these hooks as well when computing the diff to decide if changes need to be deployed.

This is relevant for any plugin deploying resources such as ConfigMap, Secrets etc. via Helm hooks. Also this is important to rollout changes in the Chart Test Hook.

### Reproduction steps

```bash
1. Deploy a Plugin that has a value that is rendered as part of a helm hook
2. Change the Plugin
3. See error, as the changed value is not deployed to the cluster
```

### PR DESCRIPTION
**Pull request by gciezkowski-acc**
## Description
I added additional check for helm hooks.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related Issue # (issue)
- Closes #459 
- Fixes # (issue)

> Remove if not applicable

## Added tests?

- [X] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🤝 Documentation pages updated
- [X] 🙅 no documentation needed
- [ ] (if applicable) generated OpenAPI docs for CRD changes

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: pkg/helm/diff.go [hunk 1]
```diff
@@ -60,6 +61,14 @@ func diffAgainstRelease(restClientGetter genericclioptions.RESTClientGetter, nam
 		return nil, err
 	}
 
+	for _, hook := range helmRelease.Hooks {
+		hookObjs, err := ObjectMapFromManifest(restClientGetter, helmRelease.Namespace, hook.Manifest, nil)
+		if err != nil {
+			return nil, err
+		}
+		maps.Copy(remoteObjs, hookObjs)
+	}
```
[the remark this answers is not in the document]
Comment (gciezkowski-acc) [reply pkg/helm/diff.go:70]: Done

File: pkg/helm/diff.go [hunk 2]
```diff
@@ -54,17 +55,33 @@ func (d DiffObjectList) String() string {
...
 		return nil, err
 	}
 
-	localObjs, err := ObjectMapFromManifest(restClientGetter, namespace, manifest, nil)
+	for _, hook := range helmRelease.Hooks {
+		hookObjs, err := ObjectMapFromManifest(restClientGetter, helmRelease.Namespace, hook.Manifest, nil)
+		if err != nil {
+			return nil, err
+		}
+		maps.Copy(remoteObjs, hookObjs)
```
Comment (IvoGoman) [inline pkg/helm/diff.go:69]: This copies from `remoteObjects` to `hookObjs`. We can expect that `remoteObjs` will be larger in most cases, so  reversing the parameters to `map.Copy()` should result in less operations.

File: pkg/helm/diff.go [hunk 3]
```diff
@@ -54,17 +55,33 @@ func (d DiffObjectList) String() string {
...
 	if err != nil {
 		return nil, err
 	}
 
+	for _, hook := range helmTemplateRelease.Hooks {
+		hookObjs, err := ObjectMapFromManifest(restClientGetter, namespace, hook.Manifest, nil)
+		if err != nil {
+			return nil, err
+		}
+		maps.Copy(localObjs, hookObjs)
```
Comment (IvoGoman) [inline pkg/helm/diff.go:82]: This copies from `remoteObjects` to `hookObjs`. We can expect that `remoteObjs` will be larger in most cases, so  reversing the parameters to `map.Copy()` should result in less operations.

File: test/e2e/fixtures/fixtures.go [hunk 4]
```diff
@@ -73,3 +73,42 @@ var NginxPluginDefinition = &greenhousev1alpha1.PluginDefinition{
...
+				Type:    "bool",
+				Default: &apiextensionsv1.JSON{Raw: []byte("false")},
+			},
+		},
+	},
+}
+
+func ptr[T any](value T) *T {
+	return &value
+}
```
Comment (IvoGoman) [inline test/e2e/fixtures/fixtures.go:114]: the `Weight` field is not required and does not make a difference for the controllers. This field is just used to order the PluginDefinitions in the UI. If you can leave out some of the other optional fields as well, this test can also use the helpers from https://github.com/cloudoperators/greenhouse/blob/main/pkg/test/resources.go#L164 

For the PluginDefinition the only thing missing afaics is the function to set the PluginOptions.

Since the rest of the tests already use the `test.TestSetup(..)` it would be nice to use them for the new test fixtures as well.

**Review by IvoGoman — CHANGES_REQUESTED** [review]

File: pkg/helm/diff.go (hunk 2 above)
Comment (gciezkowski-acc) [reply pkg/helm/diff.go:73]: `maps.Copy` function is defined as:
```go
// Copy copies all key/value pairs in src adding them to dst.
// When a key in src is already present in dst,
// the value in dst will be overwritten by the value associated
// with the key in src.
func Copy[M1 ~map[K]V, M2 ~map[K]V, K comparable, V any](dst M1, src M2) {
	for k, v := range src {
		dst[k] = v
	}
}
```
This copies from `hookObjs` to `remoteObjs` so we already have less operations.

File: pkg/helm/diff.go (hunk 3 above)
Comment (gciezkowski-acc) [reply pkg/helm/diff.go:86]: `maps.Copy` function is defined as:
```go
// Copy copies all key/value pairs in src adding them to dst.
// When a key in src is already present in dst,
// the value in dst will be overwritten by the value associated
// with the key in src.
func Copy[M1 ~map[K]V, M2 ~map[K]V, K comparable, V any](dst M1, src M2) {
	for k, v := range src {
		dst[k] = v
	}
}
```
This copies from `hookObjs` to `localObjs` so we already have less operations.

File: test/e2e/fixtures/fixtures.go (hunk 4 above)
Comment (gciezkowski-acc) [reply test/e2e/fixtures/fixtures.go]: Done

File: test/e2e/plugin_lifecycle_test.go [hunk 5]
```diff
@@ -23,126 +25,200 @@ import (
...
+				g.Expect(len(jobList.Items)).To(BeEquivalentTo(1))
+			}).Should(Succeed())
 
-		// Deleting plugin definition
-		test.EventuallyDeleted(ctx, test.K8sClient, testPluginDefinition)
+		})
 	})
 })
+
+func setOptionValueForPlugin(plugin *greenhousev1alpha1.Plugin, key, value string) {
```
Comment (IvoGoman) [inline test/e2e/plugin_lifecycle_test.go:212]: Instead of having a helper directly here in the test suite, could you add it analogous to this [one](https://github.com/cloudoperators/greenhouse/blob/747708b779a5bcfa0c603481611b4ff30d653c1d/pkg/test/resources.go#L214-L235) in the `resources.go`?

File: pkg/test/resources.go [hunk 6]
```diff
@@ -160,6 +160,13 @@ func WithHelmChart(chart *greenhousev1alpha1.HelmChartReference) func(*greenhous
 	}
 }
 
+// WithHelmChart sets the HelmChart of a PluginDefinition
```
Comment (IvoGoman) [inline pkg/test/resources.go:163]: Comment and Function name do not match

Comment (gciezkowski-acc) [reply pkg/test/resources.go]: Done
