### PR TITLE
fix(service-proxy): enhance Service Proxy URL formatting

### LINKED ISSUE #838: 🐛 [BUG] - Service Proxy not working for Perses
### Priority

(Medium) I'm annoyed but I'll live

### service-proxy logs:
```yaml
service-proxy-79677f65cf-4kqx9 2025-01-09T14:40:19Z    INFO    Forwarded request    {"host": "obs-eu-de-1--184931c.ccloud.greenhouse-qa.eu-nl-1.cloud.sap", "url": "/", "method": "GET", "status": 200, "upstream": "https://api.obs-eu-de-1.greenhouse.shoot.canary.k8s-hana.ondemand.com/api/v1/namespaces/kube-monitoring/services/http:perses:8080/proxy/"}
service-proxy-79677f65cf-4kqx9 2025-01-09T14:40:20Z    INFO    Forwarded request    {"host": "obs-eu-de-1--184931c.ccloud.greenhouse-qa.eu-nl-1.cloud.sap", "url": "/api/v1/namespaces/kube-monitoring/services/http:perses:8080/proxy/main.js", "method": "GET", "status": 404, "upstream": "https://api.obs-eu-de-1.greenhouse.shoot.canary.k8s-hana.ondemand.com/api/v1/namespaces/kube-monitoring/services/http:perses:8080/proxy/api/v1/namespaces/kube-monitoring/services/http:perses:8080/proxy/main.js"}
service-proxy-79677f65cf-4kqx9 2025-01-09T14:40:20Z    INFO    Forwarded request    {"host": "obs-eu-de-1--184931c.ccloud.greenhouse-qa.eu-nl-1.cloud.sap", "url": "/api/v1/namespaces/kube-monitoring/services/http:perses:8080/proxy/favicon.ico", "method": "GET", "status": 404, "upstream": "https://api.obs-eu-de-1.greenhouse.shoot.canary.k8s-hana.ondemand.com/api/v1/namespaces/kube-monitoring/services/http:perses:8080/proxy/api/v1/namespaces/kube-monitoring/services/http:perses:8080/proxy/favicon.ico"}
```

### Perses logs:
```yaml
perses time="2025-01-09T14:16:46Z" level=info func="github.com/perses/common/echo.(*Builder).build.Logger.LoggerWithConfig.func2.1" file="/home/runner/go/pkg/mod/github.com/perses/common@v0.26.0/echo/middleware/logger.go:63" method=GET status=200 uri=/
perses time="2025-01-09T14:16:46Z" level=info func="github.com/perses/common/echo.(*Builder).build.Logger.LoggerWithConfig.func2.1" file="/home/runner/go/pkg/mod/github.com/perses/common@v0.26.0/echo/middleware/logger.go:63" method=GET status=404 uri="/api/v1/namespaces/kube-monitoring/services/http:perses:8080/proxy/main.js"
```

### Reproduction steps

```bash
1. Go to https://obs-eu-de-1--184931c.ccloud.greenhouse-qa.eu-nl-1.cloud.sap/
2. Click F12 to check out the network tab of the browser
```

### Manifests

_No response_

### Screenshots
image

### PR DESCRIPTION
**Pull request by ibakshay**
This PR modifies the proxy URL construction to comply with the official Kubernetes API Server proxy URL format. The changes ensure correct handling of HTTP and HTTPS protocols in service proxy URLs.

Per [official Kubernetes documentation](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster-services/#manually-constructing-apiserver-proxy-urls):

> By default, the API server proxies to your service using HTTP. To use HTTPS, prefix the service name with `https:`:
> ```
> http://<kubernetes_master_address>/api/v1/namespaces/<namespace_name>/services/<service_name>/proxy
> ```

This means:
- For HTTP services (default), we should NOT prefix the service name with "http:"
- For HTTPS services, we MUST prefix the service name with "https:"

The supported formats for the `<service_name>` segment are:
* `<service_name>` - proxies to the default or unnamed port using http
* `<service_name>:<port_name>` - proxies to the specified port name or port number using http
* `https:<service_name>:` - proxies to the default or unnamed port using https
* `https:<service_name>:<port_name>` - proxies to the specified port name or port number using https

## Changes
1. Modified URL path construction in ProxyManager to:
   - Use `<service_name>:<port>` format for HTTP services (default)
   - Use `https:<service_name>:<port>` format only for HTTPS services
2. Added test cases to verify URL format for different protocol scenarios

## Test Changes
Added table-driven tests to verify URL construction for:

1. Default (no protocol) -> HTTP format
2. Explicit HTTP protocol -> HTTP format
3. Explicit HTTPS protocol -> HTTPS format

Partially resolves #838

### CODE REVIEW

File: cmd/service-proxy/proxy_test.go [hunk 1]
```diff
@@ -159,3 +159,102 @@ users:
...
+				t.Errorf("expected no error, got: %s", err)
+			}
+
+			route, ok := pm.clusters["cluster-1"].routes["https://cluster-1--1234567.org.basedomain"]
+			if !ok {
+				t.Fatal("expected route to be added")
+			}
+
+			targetURL := route.url
+			expectedURL := fmt.Sprintf("https://apiserver.test%s", tc.expectedURLPath)
```
Comment (kengou) [inline cmd/service-proxy/proxy_test.go:249]: `Error: cmd/service-proxy/proxy_test.go:249:19: fmt.Sprintf can be replaced with string concatenation (perfsprint)`
Can you please fix this, then the linting should pass

**Review by kengou — CHANGES_REQUESTED** [review]

**Review by IvoGoman — COMMENTED** [review]
Thanks for bringing this up

**Review by IvoGoman — APPROVED** [review]

**Review by kengou — APPROVED** [review]
