### PR TITLE
fix(e2e): removes deprecated fields from the appProps.json creation

### LINKED ISSUE #1048: 🐛 [BUG] - Outdated appProps breaking login to 'demo' org
### Priority

None

### Description

When trying to run the dev-env, demo org, it is not possible to access the cluster page.

### Reproduction steps

```bash
1. make setup PLUGIN_DIR=../extensions-greenhouse
1. nohup kubectl port-forward svc/greenhouse-cors-proxy 9090:80 -n greenhouse 2>&1 > /dev/null &
1. nohup kubectl port-forward svc/greenhouse-dashboard 5001:80 -n greenhouse 2>&1 > /dev/null &
1. Go to `http://localhost:5001/?org=demo`
1. See Browser Console log:



[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (demo, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (demo, line 0)
```

### Manifests

```yaml

```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### PR DESCRIPTION
**Pull request by olandr**
## Description

- Removes 'mockAuth' from the default appProps.json (deprecated in juno)
- Removes 'environment' from charts/dashboards (deprecated in juno, [commit](https://github.com/cloudoperators/juno/pull/706/commits/15de11203007c3c9e46002b9b81cf2f222ed6f8b))

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1048

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🤝 Documentation pages updated
- [x] 🙅 no documentation needed
- [ ] (if applicable) generated OpenAPI docs for CRD changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by IvoGoman — COMMENTED** [review]
Could you bump the dashboard chart?

File: pkg/internal/local/setup/dashboard.go [hunk 1]
```diff
@@ -200,7 +199,6 @@ func (m *Manifest) modifyDashboardProps(ctx context.Context, cl client.Client, c
 		return nil, errors.New("empty token found in service account secret")
 	}
 	props[apiEndpointKey] = apiProxyURL
-	props[mockAuthKey] = "true"
```
Comment (abhijith-darshan) [inline pkg/internal/local/setup/dashboard.go:203]: I think the usage should be either `mockAuth` or `demoUserToken`

Comment (abhijith-darshan) [reply pkg/internal/local/setup/dashboard.go:203]: @ArtieReus - can you confirm?

Comment (ArtieReus) [reply pkg/internal/local/setup/dashboard.go:203]: Confirmed. The correct appProps are either `mockAuth` or `demoUserToken`, depending on the use case. If both are set, `mockAuth` takes precedence over `demoUserToken`
Please refer to the readme of the dashboard:
https://github.com/cloudoperators/juno/blob/main/apps/greenhouse/README.md#app-props

Comment (olandr) [reply pkg/internal/local/setup/dashboard.go:203]: So should we enforce the xor here somehow? If yes, we should probably also check if `mockAuth` complies on the specified format (as written in the README)?

That said, by using "true" I received the error highlighted in https://github.com/cloudoperators/greenhouse/issues/1048#issuecomment-2772076730. By removing the entry, as suggested, the `demoUserToken` was taken instead and the problem was resolved.

Comment (ArtieReus) [reply pkg/internal/local/setup/dashboard.go:203]: The `mockAuth` option was originally introduced to bypass OIDC authentication when developing applications against backends that didn't require authentication (e.g., Supernova, Doop, or Heureka). When set, `mockAuth` takes precedence over both real and token-based authentication, regardless of the organization provided. This means that even if `demoOrg` and `demoUserToken` are correctly set and `demoOrg` passed through the browser, mock data will still be sent to the backend. 
Token authentication will only work if `mockAuth` is NOT set and the demoOrg matches the organization being used. 
For the new development setup, mockAuth should no longer be used. I’ll add this clarification to the README of the Greenhouse application.

Comment (IvoGoman) [reply pkg/internal/local/setup/dashboard.go:203]: Ok, then we can go ahead with the proposed changes 👍

**Review by IvoGoman — DISMISSED** [review]

**Comment by IvoGoman** [comment]
@olandr could you rebase once on main? With #989 the repo got restructured and the file is now unter `internal/local/setup/dashboard.go`

**Review by IvoGoman — APPROVED** [review]
